#
#Sat Jun 13 05:04:56 UTC 2026
acceptInsecureCerts=true
browserName=chrome
goog\:chromeOptions={args\=[test-type, no-sandbox, ignore-certificate-errors, --window-size\=1280,1024, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, headless, test-type, no-sandbox, ignore-certificate-errors, --window-size\=1280,1024, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, headless, remote-allow-origins\=*], extensions\=[]}
