webdriver.driver=chrome
webdriver.base.url=http://localhost:8080
headless.mode=true
serenity.take.screenshots=FOR_FAILURES
chrome.switches=--no-sandbox;--ignore-certificate-errors;--window-size=1280,1024;--incognito;--disable-gpu;--headless
